### ISSUE TITLE
Mobile app for kicker game

### ISSUE THREAD

**Issue by skonair** [SmartsquareGmbH/kickchain#8]
Create a mobile app to 
- start a kicker game (setup players)
(- let players agree on a game)
- add the game to the blockchain via fullnode call

**Comment by deen13** [comment]
iOS Support would be awesome @rubengees  :tada: :laughing:

**Comment by rubengees** [comment]
😅

**Comment by rubengees** [comment]
[Done!](https://github.com/SmartsquareGmbH/kickdroid)
